builds:
- binary: onstatic
  env:
    - CGO_ENABLED=0
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - 386
    - amd64
  main: ./cmd/server/main.go
- binary: plugin
  env:
    - CGO_ENABLED=0
  goos:
    - darwin
  goarch:
    - amd64
  flags:
    - -buildmode=plugin
    - -o
    - build/example.so
  main: ./plugins/example/main.go
